### ISSUE TITLE
Launchable CLI verify command does not work on windows agents

### ISSUE THREAD

**Issue by GunnyDev** [launchableinc/cli#186]
### Context
Testing Launchable on a Monolithic .Net 4.7.2 Application that can only be build using windows agents.

### Current Behaviour
The `launchable verify` command returns the error `[WinError 2] The system cannot find the file specified` when attempting to check the java version, on a windows environment. This is because in  [java.py](https://github.com/launchableinc/cli/blob/596381e93557b7e5bb9edd8a87c99b8952d24e35/launchable/utils/java.py#L6), **"which"** is being used to locate Java `res = subprocess.run(["which", "java"], stdout=subprocess.DEVNULL)` this does not work on windows. 

### Expected Behaviour
The `launchable verify`  command to work successfully on a windows environment

### Possible Solution
Inside [java.py](https://github.com/launchableinc/cli/blob/596381e93557b7e5bb9edd8a87c99b8952d24e35/launchable/utils/java.py#L6) make a check on the current system, and if windows use **'where'** to locate java and check the version
`   res = subprocess.run(["where", "java"], stdout=subprocess.DEVNULL)`

**Comment by Konboi** [comment]
@GunnyDev 

Thank you for your investigation and suggestion,
Our team will discuss the Windows support. 

So, please wait a moment to support it.
