### ISSUE TITLE
Consider changing this to sha256

### ISSUE THREAD

**Issue by ctennis** [launchableinc/cli#280]
https://github.com/launchableinc/cli/blob/54c740a849367f8468316c381833e49790240efb/launchable/utils/session.py#L18

Reason: even though this is not an insecure use of this hash, the fact that we use sha1 is a thing that would be easier to not to have to explain to a prospect/customer, especially if they're running this on their premises. It may make the infosec story easier to explain if we don't have to talk about it.

**Comment by ctennis** [comment]
found via sonarqube

**Comment by Konboi** [comment]
We fixed not to use this method. So, I close this issue
