### ISSUE TITLE
click.echo not an exception

### ISSUE THREAD

**Issue by ctennis** [launchableinc/cli#281]
https://github.com/launchableinc/cli/blob/54c740a849367f8468316c381833e49790240efb/launchable/commands/record/tests.py#L331

https://sonarcloud.io/project/issues?id=launchableinc_cli&issues=AXtA0_Hv5z-0hzjkVX3T&open=AXtA0_Hv5z-0hzjkVX3T

Should this be raised, and if so, does it need to derive from Exception?

**Comment by Konboi** [comment]
fixed
