### ISSUE TITLE
launchable record tests fail with "Invalid format" message

### ISSUE THREAD

**Issue by ebyhr** [launchableinc/cli#328]
I'm testing launchable CLI in https://github.com/trinodb/trino repository, but I faced the below error. 

```bash
$ launchable record build --name GITHUB_RUN_ID
$ ./mvnw install -pl :trino-test-jdbc-compatibility-old-server
$ launchable record tests --build GITHUB_RUN_ID maven ./testing/trino-test-jdbc-compatibility-old-server/target/surefire-reports/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/launchable/commands/record/tests.py", line 288, in run
    raise Exception(exceptions)
Exception: [Exception([Exception('Failed to process a report file: ./testing/trino-test-jdbc-compatibility-old-server/target/surefire-reports/testng-results.xml', JUnitXmlError('Invalid format.'))])]
```

Attached the surefire reports. This is my first use, so sorry if my setup is wrong. 
[surefire-reports.zip](https://github.com/launchableinc/cli/files/7497519/surefire-reports.zip)

**Comment by Konboi** [comment]
@ebyhr Thank you for trying to use Launchable.
Please change target directory `./testing/trino-test-jdbc-compatibility-old-server/target/surefire-reports/` 
 to `./testing/trino-test-jdbc-compatibility-old-server/target/surefire-reports/junitreports/` (added junitreports directory)and try again

I don't know how was generated test-result.xml. But it's not JUnit file format.

**Comment by ebyhr** [comment]
@Konboi Thanks! I can execute the command now. Let me close this issue.
